# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "controll"
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kristian Mandrup"]
  s.date = "2012-12-07"
  s.description = "Flow, Executor, Notifier and more, all tied together tool pack"
  s.email = "kmandrup@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "controll.gemspec",
    "lib/controll.rb",
    "lib/controll/assistant.rb",
    "lib/controll/assistant/param_assistant.rb",
    "lib/controll/assistant/session_assistant.rb",
    "lib/controll/command.rb",
    "lib/controll/commander.rb",
    "lib/controll/enabler.rb",
    "lib/controll/enabler/macros.rb",
    "lib/controll/enabler/maps.rb",
    "lib/controll/enabler/notify.rb",
    "lib/controll/enabler/path_handler.rb",
    "lib/controll/enabler/path_resolver.rb",
    "lib/controll/engine.rb",
    "lib/controll/errors.rb",
    "lib/controll/event.rb",
    "lib/controll/event/helper.rb",
    "lib/controll/event/matcher.rb",
    "lib/controll/events.rb",
    "lib/controll/executor.rb",
    "lib/controll/executor/base.rb",
    "lib/controll/executor/controlled.rb",
    "lib/controll/executor/delegator.rb",
    "lib/controll/flow.rb",
    "lib/controll/flow/action.rb",
    "lib/controll/flow/action/base.rb",
    "lib/controll/flow/action/fallback.rb",
    "lib/controll/flow/action/path_action.rb",
    "lib/controll/flow/action_mapper.rb",
    "lib/controll/flow/action_mapper/base.rb",
    "lib/controll/flow/action_mapper/complex.rb",
    "lib/controll/flow/action_mapper/simple.rb",
    "lib/controll/flow/errors.rb",
    "lib/controll/flow/event_mapper.rb",
    "lib/controll/flow/event_mapper/path_finder.rb",
    "lib/controll/flow/event_mapper/util.rb",
    "lib/controll/flow/master.rb",
    "lib/controll/flow/master/executor.rb",
    "lib/controll/flow/master/macros.rb",
    "lib/controll/focused/enabler.rb",
    "lib/controll/helper.rb",
    "lib/controll/helper/hash_access.rb",
    "lib/controll/helper/params.rb",
    "lib/controll/helper/session.rb",
    "lib/controll/macros.rb",
    "lib/controll/notify.rb",
    "lib/controll/notify/base.rb",
    "lib/controll/notify/flash.rb",
    "lib/controll/notify/macros.rb",
    "lib/controll/notify/message.rb",
    "lib/controll/notify/message/handler.rb",
    "lib/controll/notify/message/resolver.rb",
    "lib/controll/notify/message/translator.rb",
    "lib/controll/notify/typed.rb",
    "lib/generators/controll/assistant_generator.rb",
    "lib/generators/controll/executor_generator.rb",
    "lib/generators/controll/flow_handler_generator.rb",
    "lib/generators/controll/notifier_generator.rb",
    "lib/generators/controll/setup_generator.rb",
    "lib/generators/controll/templates/assistant.tt",
    "lib/generators/controll/templates/commander.tt",
    "lib/generators/controll/templates/executor.tt",
    "lib/generators/controll/templates/flow_handler.tt",
    "lib/generators/controll/templates/notifier.tt",
    "spec/acceptance/app_test.rb",
    "spec/controll/assistant/param_assistant_spec.rb",
    "spec/controll/assistant/session_assistant_spec.rb",
    "spec/controll/assistant_spec.rb",
    "spec/controll/command_spec.rb",
    "spec/controll/commander_spec.rb",
    "spec/controll/enabler/macros_spec.rb",
    "spec/controll/enabler/maps_spec.rb",
    "spec/controll/enabler/notify_spec.rb",
    "spec/controll/enabler/path_handler_spec.rb",
    "spec/controll/enabler/path_resolver_spec.rb",
    "spec/controll/enabler_spec.rb",
    "spec/controll/event/helper_spec.rb",
    "spec/controll/event/matcher_spec.rb",
    "spec/controll/event_spec.rb",
    "spec/controll/events_spec.rb",
    "spec/controll/executor/controlled_spec.rb",
    "spec/controll/executor/delegator_spec.rb",
    "spec/controll/flow/action_mapper/complex_spec.rb",
    "spec/controll/flow/action_mapper/fallback_spec.rb",
    "spec/controll/flow/action_mapper/simple_spec.rb",
    "spec/controll/flow/event_mapper/path_finder_spec.rb",
    "spec/controll/flow/event_mapper/util_spec.rb",
    "spec/controll/flow/master/executor_spec.rb",
    "spec/controll/flow/master/macros_spec.rb",
    "spec/controll/flow/master_spec.rb",
    "spec/controll/helper/hash_access_spec.rb",
    "spec/controll/helper/params_spec.rb",
    "spec/controll/helper/session_spec.rb",
    "spec/controll/notify/base_spec.rb",
    "spec/controll/notify/flash_spec.rb",
    "spec/controll/notify/message/handler_spec.rb",
    "spec/controll/notify/message/resolver_spec.rb",
    "spec/controll/notify/message/translator_spec.rb",
    "spec/controll/notify/message_spec.rb",
    "spec/controll/notify/services_notifier.rb",
    "spec/controll/notify/typed_spec.rb",
    "spec/controll_app/.gitignore",
    "spec/controll_app/Gemfile",
    "spec/controll_app/Gemfile.lock",
    "spec/controll_app/README.rdoc",
    "spec/controll_app/Rakefile",
    "spec/controll_app/app/controll/commanders/services_commander.rb",
    "spec/controll_app/app/controll/executors/services_executor.rb",
    "spec/controll_app/app/controll/flows/create_services.rb",
    "spec/controll_app/app/controll/notifiers/services_notifier.rb",
    "spec/controll_app/app/controllers/application_controller.rb",
    "spec/controll_app/app/controllers/services_controller.rb",
    "spec/controll_app/app/models/.gitkeep",
    "spec/controll_app/app/models/post.rb",
    "spec/controll_app/app/views/layouts/application.html.erb",
    "spec/controll_app/app/views/posts/_form.html.erb",
    "spec/controll_app/app/views/posts/edit.html.erb",
    "spec/controll_app/app/views/posts/index.html.erb",
    "spec/controll_app/app/views/posts/new.html.erb",
    "spec/controll_app/app/views/posts/show.html.erb",
    "spec/controll_app/config.ru",
    "spec/controll_app/config/application.rb",
    "spec/controll_app/config/boot.rb",
    "spec/controll_app/config/environment.rb",
    "spec/controll_app/config/environments/development.rb",
    "spec/controll_app/config/environments/test.rb",
    "spec/controll_app/config/initializers/backtrace_silencers.rb",
    "spec/controll_app/config/initializers/inflections.rb",
    "spec/controll_app/config/initializers/mime_types.rb",
    "spec/controll_app/config/initializers/secret_token.rb",
    "spec/controll_app/config/initializers/session_store.rb",
    "spec/controll_app/config/locales/en.yml",
    "spec/controll_app/config/routes.rb",
    "spec/controll_app/db/seeds.rb",
    "spec/controll_app/log/.gitkeep",
    "spec/controll_app/public/404.html",
    "spec/controll_app/public/422.html",
    "spec/controll_app/public/500.html",
    "spec/controll_app/public/favicon.ico",
    "spec/controll_app/public/index.html",
    "spec/controll_app/public/javascripts/application.js",
    "spec/controll_app/public/robots.txt",
    "spec/controll_app/public/stylesheets/application.css",
    "spec/functional_test_helper.rb",
    "spec/helper.rb",
    "spec/rspec_controller_class.rb",
    "spec/rspec_functional_helper.rb",
    "spec/rspec_helper.rb",
    "spec/spec_helper.rb",
    "spec/test_helper.rb",
    "spec/unit/functional_test_helper_test.rb",
    "spec/unit/macros_test.rb",
    "spec/unit/mixin_test.rb",
    "spec/unit/rspec_functional_helper.rb",
    "spec/unit/rspec_helper_test.rb",
    "spec/unit/test_helper_test.rb"
  ]
  s.homepage = "http://github.com/kristianmandrup/controll"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Utils for handling complex Controller/Business logic"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<hashie>, ["~> 1.2"])
      s.add_runtime_dependency(%q<liquid>, [">= 0"])
      s.add_runtime_dependency(%q<imperator-ext>, ["~> 0.2.0"])
      s.add_runtime_dependency(%q<focused_controller>, [">= 0"])
      s.add_runtime_dependency(%q<i18n>, [">= 0.6"])
      s.add_runtime_dependency(%q<rails>, ["~> 3"])
      s.add_development_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_development_dependency(%q<rdoc>, [">= 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>, [">= 1.8.4"])
      s.add_development_dependency(%q<simplecov>, [">= 0.5"])
    else
      s.add_dependency(%q<hashie>, ["~> 1.2"])
      s.add_dependency(%q<liquid>, [">= 0"])
      s.add_dependency(%q<imperator-ext>, ["~> 0.2.0"])
      s.add_dependency(%q<focused_controller>, [">= 0"])
      s.add_dependency(%q<i18n>, [">= 0.6"])
      s.add_dependency(%q<rails>, ["~> 3"])
      s.add_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_dependency(%q<rdoc>, [">= 3.12"])
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>, [">= 1.8.4"])
      s.add_dependency(%q<simplecov>, [">= 0.5"])
    end
  else
    s.add_dependency(%q<hashie>, ["~> 1.2"])
    s.add_dependency(%q<liquid>, [">= 0"])
    s.add_dependency(%q<imperator-ext>, ["~> 0.2.0"])
    s.add_dependency(%q<focused_controller>, [">= 0"])
    s.add_dependency(%q<i18n>, [">= 0.6"])
    s.add_dependency(%q<rails>, ["~> 3"])
    s.add_dependency(%q<rspec>, [">= 2.8.0"])
    s.add_dependency(%q<rdoc>, [">= 3.12"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>, [">= 1.8.4"])
    s.add_dependency(%q<simplecov>, [">= 0.5"])
  end
end

