# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "controll"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kristian Mandrup"]
  s.date = "2012-08-16"
  s.description = "FlowHandler, Executor, Notifier and more, all tied together tool pack"
  s.email = "kmandrup@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "controll.gemspec",
    "lib/controll.rb",
    "lib/controll/assistant.rb",
    "lib/controll/command.rb",
    "lib/controll/commander.rb",
    "lib/controll/errors.rb",
    "lib/controll/executor.rb",
    "lib/controll/executor/base.rb",
    "lib/controll/executor/notificator.rb",
    "lib/controll/flow_handler.rb",
    "lib/controll/flow_handler/base.rb",
    "lib/controll/flow_handler/control.rb",
    "lib/controll/flow_handler/errors.rb",
    "lib/controll/flow_handler/event_helper.rb",
    "lib/controll/flow_handler/redirect.rb",
    "lib/controll/flow_handler/redirect/action.rb",
    "lib/controll/flow_handler/redirect/mapper.rb",
    "lib/controll/flow_handler/render.rb",
    "lib/controll/helper.rb",
    "lib/controll/helper/event_matcher.rb",
    "lib/controll/helper/hash_access.rb",
    "lib/controll/helper/notify.rb",
    "lib/controll/helper/params.rb",
    "lib/controll/helper/path_resolver.rb",
    "lib/controll/helper/session.rb",
    "lib/controll/notify.rb",
    "lib/controll/notify/base.rb",
    "lib/controll/notify/flash.rb",
    "lib/controll/notify/typed.rb",
    "spec/acceptance/app_test.rb",
    "spec/app/.gitignore",
    "spec/app/Gemfile",
    "spec/app/Gemfile.lock",
    "spec/app/README.rdoc",
    "spec/app/Rakefile",
    "spec/app/app/controllers/application_controller.rb",
    "spec/app/app/controllers/posts_controller.rb",
    "spec/app/app/models/.gitkeep",
    "spec/app/app/models/post.rb",
    "spec/app/app/views/layouts/application.html.erb",
    "spec/app/app/views/posts/_form.html.erb",
    "spec/app/app/views/posts/edit.html.erb",
    "spec/app/app/views/posts/index.html.erb",
    "spec/app/app/views/posts/new.html.erb",
    "spec/app/app/views/posts/show.html.erb",
    "spec/app/config.ru",
    "spec/app/config/application.rb",
    "spec/app/config/boot.rb",
    "spec/app/config/environment.rb",
    "spec/app/config/environments/development.rb",
    "spec/app/config/environments/test.rb",
    "spec/app/config/initializers/backtrace_silencers.rb",
    "spec/app/config/initializers/inflections.rb",
    "spec/app/config/initializers/mime_types.rb",
    "spec/app/config/initializers/secret_token.rb",
    "spec/app/config/initializers/session_store.rb",
    "spec/app/config/locales/en.yml",
    "spec/app/config/routes.rb",
    "spec/app/db/seeds.rb",
    "spec/app/lib/assets/.gitkeep",
    "spec/app/lib/tasks/.gitkeep",
    "spec/app/log/.gitkeep",
    "spec/app/public/404.html",
    "spec/app/public/422.html",
    "spec/app/public/500.html",
    "spec/app/public/favicon.ico",
    "spec/app/public/index.html",
    "spec/app/public/javascripts/application.js",
    "spec/app/public/robots.txt",
    "spec/app/public/stylesheets/application.css",
    "spec/app/script/rails",
    "spec/app/spec/controllers/posts_controller_spec.rb",
    "spec/app/spec/isolated_spec_helper.rb",
    "spec/app/spec/spec_helper.rb",
    "spec/app/spec/unit/controllers/posts_controller_isolated_spec.rb",
    "spec/app/spec/unit/controllers/posts_controller_spec.rb",
    "spec/app/test/functional/.gitkeep",
    "spec/app/test/functional/posts_controller_test.rb",
    "spec/app/test/isolated_test_helper.rb",
    "spec/app/test/test_helper.rb",
    "spec/app/test/unit/.gitkeep",
    "spec/app/test/unit/controllers/posts_controller_isolated_test.rb",
    "spec/app/test/unit/controllers/posts_controller_test.rb",
    "spec/app/vendor/assets/javascripts/.gitkeep",
    "spec/app/vendor/assets/stylesheets/.gitkeep",
    "spec/app/vendor/plugins/.gitkeep",
    "spec/controll/asssistant_spec.rb",
    "spec/controll/command_spec.rb",
    "spec/controll/commander_spec.rb",
    "spec/controll/executor/notificator_spec.rb",
    "spec/controll/flow_handler/control_spec.rb",
    "spec/controll/flow_handler/redirect/action_spec.rb",
    "spec/controll/flow_handler/redirect/mapper_spec.rb",
    "spec/controll/flow_handler/redirect_spec.rb",
    "spec/controll/flow_handler/render_spec.rb",
    "spec/controll/helper/event_matcher_spec.rb",
    "spec/controll/helper/hash_access_spec.rb",
    "spec/controll/helper/notify_spec.rb",
    "spec/controll/helper/params_spec.rb",
    "spec/controll/helper/path_resolver_spec.rb",
    "spec/controll/helper/session_spec.rb",
    "spec/controll/helper_spec.rb",
    "spec/controll/notify/base_spec.rb",
    "spec/controll/notify/flash_spec.rb",
    "spec/controll/notify/message_handler.rb",
    "spec/controll/notify/typed_spec.rb",
    "spec/functional_test_helper.rb",
    "spec/helper.rb",
    "spec/rspec_controller_class.rb",
    "spec/rspec_functional_helper.rb",
    "spec/rspec_helper.rb",
    "spec/spec_helper.rb",
    "spec/test_helper.rb",
    "spec/unit/functional_test_helper_test.rb",
    "spec/unit/macros_test.rb",
    "spec/unit/mixin_test.rb",
    "spec/unit/rspec_functional_helper.rb",
    "spec/unit/rspec_helper_test.rb",
    "spec/unit/test_helper_test.rb"
  ]
  s.homepage = "http://github.com/kristianmandrup/controll"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Utils for handling complex Controller/Business logic"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<hashie>, ["~> 1.2"])
      s.add_runtime_dependency(%q<liquid>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_development_dependency(%q<rdoc>, [">= 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>, [">= 1.8.4"])
      s.add_development_dependency(%q<simplecov>, [">= 0.5"])
    else
      s.add_dependency(%q<hashie>, ["~> 1.2"])
      s.add_dependency(%q<liquid>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_dependency(%q<rdoc>, [">= 3.12"])
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>, [">= 1.8.4"])
      s.add_dependency(%q<simplecov>, [">= 0.5"])
    end
  else
    s.add_dependency(%q<hashie>, ["~> 1.2"])
    s.add_dependency(%q<liquid>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 2.8.0"])
    s.add_dependency(%q<rdoc>, [">= 3.12"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>, [">= 1.8.4"])
    s.add_dependency(%q<simplecov>, [">= 0.5"])
  end
end

